apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
resources:
- ../base
images:
- name: humancat-frontend-image
  newName: 866477832211.dkr.ecr.ap-southeast-2.amazonaws.com/humancat-frontend
  newTag: "20240523.142101"
namespace: gitops
