apiVersion: v1
kind: Service
metadata:
  name: humancat-backend-svc
spec:
  type: ClusterIP
  selector:
    app: humancat-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: api-port