apiVersion: apps/v1
kind: Deployment
metadata:
  name: humancat-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: humancat-backend
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"