apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
resources:
- ../base
images:
- name: humancat-backend-image
  newName: <ECR레포지토리>
  newTag: <이미지태그>
namespace: gitops
