apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
resources:
- ../base
images:
- name: humancat-backend-image
  newName: 866477832211.dkr.ecr.ap-southeast-2.amazonaws.com/humancat-backend
  newTag: 0.0.1-backend.10
namespace: gitops
