apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yml
- service_canary.yml
- ingress.yml
images:
- name: humancat-frontend-canary-rollout-image
  newName: <ECR레포지토리>
  newTag: <이미지태그>
namespace: gitops
