name: outputtest
on: workflow_dispatch
jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.def_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - id: def_tag
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "tag=$(date +'%Y%m%d.%H%M%S')" >> "$GITHUB_OUTPUT"
      - name: check tag value
        run: |
          echo ${{ steps.def_tag.outputs.tag }}
  verify:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: call
        run: |
          echo "value is ${{ needs.versioning.outputs.tags }}"
